stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

test:
  stage: test
  image: mcr.microsoft.com/playwright/python
  before_script:
    - python -m pip install --upgrade pip
    - cd selenium-project
    - pip install -r requirements.txt
  script:
    - pytest --tb=short -ra --headless
  only:
    - non-existent-branch